/*  Lab Question
 *  Write a Java program using Swing that demonstrates the use of different layout managers (FlowLayout, GridLayout, and BorderLayout).
•	Divide the main frame into three panels using BorderLayout:
o	North Panel: Use FlowLayout to arrange three labels (Name, Roll No, Class) in a single row.
o	Center Panel: Use GridLayout (3x2) to create a simple login form with two text fields (Username, Password), a JCheckBox (“Remember Me”), and a JButton (“Login”).
o	South Panel: Use FlowLayout to add two buttons (Reset and Exit).
•	Handle events so that:
o	When Login is pressed, display the entered username in a message dialog.
o	When Reset is pressed, clear the text fields.
o	When Exit is pressed, close the program.

 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * A Java Swing application demonstrating the use of FlowLayout, GridLayout,
 * and BorderLayout to create a structured GUI.
 */
public class LayoutManager extends JFrame implements ActionListener {

    private JTextField usernameField;
    private JPasswordField passwordField;

    /**
     * Constructs the main application frame and sets up all components and panels.
     */
    public LayoutManager() {
        super("Layout Manager");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLayout(new BorderLayout(10, 10)); // Main frame uses BorderLayout

        // --- North Panel with FlowLayout ---
        JPanel northPanel = new JPanel();
        northPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 10));
        northPanel.setBorder(BorderFactory.createTitledBorder("Student Details"));
        northPanel.add(new JLabel("Name:"));
        northPanel.add(new JLabel("Roll No:"));
        northPanel.add(new JLabel("Class:"));
        this.add(northPanel, BorderLayout.NORTH);

        // --- Center Panel with GridLayout ---
        JPanel centerPanel = new JPanel();
        centerPanel.setLayout(new GridLayout(3, 2, 10, 10));
        centerPanel.setBorder(BorderFactory.createTitledBorder("Login Form"));

        this.usernameField = new JTextField(20);
        this.passwordField = new JPasswordField(20);
        
        centerPanel.add(new JLabel("Username:"));
        centerPanel.add(this.usernameField);
        centerPanel.add(new JLabel("Password:"));
        centerPanel.add(this.passwordField);
        centerPanel.add(new JCheckBox("Remember Me"));
        JButton loginButton = new JButton("Login");
        loginButton.addActionListener(this);
        centerPanel.add(loginButton);
        this.add(centerPanel, BorderLayout.CENTER);

        // --- South Panel with FlowLayout ---
        JPanel southPanel = new JPanel();
        southPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 10));
        JButton resetButton = new JButton("Reset");
        JButton exitButton = new JButton("Exit");
        
        resetButton.addActionListener(this);
        exitButton.addActionListener(this);

        southPanel.add(resetButton);
        southPanel.add(exitButton);
        this.add(southPanel, BorderLayout.SOUTH);

        // Pack the frame to its preferred size and make it visible
        this.pack();
        this.setLocationRelativeTo(null); // Center the frame
        this.setVisible(true);
    }

    /**
     * Handles action events from the buttons.
     * @param e The ActionEvent generated by a button click.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        String command = e.getActionCommand();

        switch (command) {
            case "Login":
                String username = usernameField.getText();
                JOptionPane.showMessageDialog(this, "Logged in as: " + username);
                break;
            case "Reset":
                usernameField.setText("");
                passwordField.setText("");
                break;
            case "Exit":
                System.exit(0);
                break;
        }
    }

    /**
     * Main method to run the application.
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(LayoutManager::new);
    }
}
